# Generated by Django 5.2.6 on 2025-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_DB',
            fields=[
                ('Movie_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=20)),
                ('Rating', models.IntegerField()),
                ('Language', models.CharField(max_length=15)),
                ('Release_Date', models.DateField()),
                ('Poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
